kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-web-role-binding
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-admin
subjects:
- kind: Group
  name: 187123c4-d2a7-4fd9-b8b7-f1dfe57093bf
  apiGroup: rbac.authorization.k8s.io