apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-minimal-ingress
  namespace: web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tripviewer-svc-lb
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-minimal-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /api/poi
        pathType: Prefix
        backend:
          service:
            name: poi-svc
            port:
              number: 80
      - path: /swagger/docs/poi
        pathType: Prefix
        backend:
          service:
            name: poi-svc
            port:
              number: 80
      - path: /api/docs/poi
        pathType: Prefix
        backend:
          service:
            name: poi-svc
            port:
              number: 80
      - path: /api/user-java
        pathType: Prefix
        backend:
          service:
            name: java-svc
            port:
              number: 80
      - path: /api/trips
        pathType: Prefix
        backend:
          service:
            name: trip-svc
            port:
              number: 80
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: userprofile-svc
            port:
              number: 80