kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-web-role-binding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: Azure Kubernetes Service RBAC Reader
subjects:
- kind: Group
  namespace: web
  name: 187123c4-d2a7-4fd9-b8b7-f1dfe57093bf
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-api-role-binding
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: Azure Kubernetes Service RBAC Writer
subjects:
- kind: Group
  namespace: api
  name: 187123c4-d2a7-4fd9-b8b7-f1dfe57093bf
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-web-role-binding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: Azure Kubernetes Service RBAC Writer
subjects:
- kind: Group
  namespace: web
  name: d8cead56-8894-4598-a205-4057f6e677ac
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-api-role-binding
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: Azure Kubernetes Service RBAC Reader
subjects:
- kind: Group
  namespace: api
  name: d8cead56-8894-4598-a205-4057f6e677ac